<!DOCTYPE datafile [<!ELEMENT datafile ANY>	<!ELEMENT header ANY>		<!ELEMENT emu_name (#PCDATA)>		<!ELEMENT emu_parser (#PCDATA)>		<!ELEMENT emu_description (#PCDATA)>		<!ELEMENT emu_category (#PCDATA)>		<!ELEMENT emu_version (#PCDATA)>		<!ELEMENT emu_date (#PCDATA)>		<!ELEMENT emu_author (#PCDATA)>		<!ELEMENT emu_homepage (#PCDATA)>		<!ELEMENT emu_baseurl (#PCDATA)>		<!ELEMENT emu_launcher (#PCDATA)>		<!ELEMENT emu_ext_launch_cmd (#PCDATA)>		<!ELEMENT emu_downloadpath (#PCDATA)>		<!ELEMENT emu_postdlaction (#PCDATA)>		<!ELEMENT emu_comment (#PCDATA)>		<!ELEMENT emu_thumb (#PCDATA)>		<!ELEMENT emu_banner (#PCDATA)>		<!ELEMENT emu_fanart (#PCDATA)>		<!ELEMENT emu_logo (#PCDATA)>		<!ELEMENT emu_trailer (#PCDATA)>	<!ELEMENT game ANY>		<!ATTLIST game name CDATA #REQUIRED>		<!ELEMENT description (#PCDATA)>		<!ELEMENT rom EMPTY>			<!ATTLIST rom name CDATA #REQUIRED>			<!ATTLIST rom size CDATA #REQUIRED>			<!ATTLIST rom crc CDATA #IMPLIED>			<!ATTLIST rom sha1 CDATA #IMPLIED>			<!ATTLIST rom status (baddump|nodump|good|verified) "good">		<!ELEMENT videoid (#PCDATA)>		<!ELEMENT plot (#PCDATA)>		<!ELEMENT genre (#PCDATA)>		<!ELEMENT nplayers (#PCDATA)>		<!ELEMENT studio (#PCDATA)>		<!ELEMENT releasedate (#PCDATA)>		<!ELEMENT fanart1 (#PCDATA)>		<!ELEMENT fanart2 (#PCDATA)>		<!ELEMENT fanart3 (#PCDATA)>		<!ELEMENT fanart4 (#PCDATA)>		<!ELEMENT fanart5 (#PCDATA)>		<!ELEMENT fanart6 (#PCDATA)>		<!ELEMENT fanart7 (#PCDATA)>		<!ELEMENT fanart8 (#PCDATA)>		<!ELEMENT fanart9 (#PCDATA)>		<!ELEMENT fanart10 (#PCDATA)>		<!ELEMENT fanart11 (#PCDATA)>		<!ELEMENT fanart12 (#PCDATA)>		<!ELEMENT fanart13 (#PCDATA)>		<!ELEMENT fanart14 (#PCDATA)>		<!ELEMENT fanart15 (#PCDATA)>		<!ELEMENT fanart16 (#PCDATA)>		<!ELEMENT fanart17 (#PCDATA)>		<!ELEMENT fanart18 (#PCDATA)>		<!ELEMENT fanart19 (#PCDATA)>		<!ELEMENT fanart20 (#PCDATA)>		<!ELEMENT fanart21 (#PCDATA)>		<!ELEMENT fanart22 (#PCDATA)>		<!ELEMENT fanart23 (#PCDATA)>		<!ELEMENT fanart24 (#PCDATA)>		<!ELEMENT fanart25 (#PCDATA)>		<!ELEMENT fanart26 (#PCDATA)>		<!ELEMENT fanart27 (#PCDATA)>		<!ELEMENT fanart28 (#PCDATA)>		<!ELEMENT fanart29 (#PCDATA)>		<!ELEMENT fanart30 (#PCDATA)>		<!ELEMENT boxart1 (#PCDATA)>		<!ELEMENT boxart2 (#PCDATA)>		<!ELEMENT boxart3 (#PCDATA)>		<!ELEMENT boxart4 (#PCDATA)>		<!ELEMENT boxart5 (#PCDATA)>		<!ELEMENT boxart6 (#PCDATA)>		<!ELEMENT boxart7 (#PCDATA)>		<!ELEMENT boxart8 (#PCDATA)>		<!ELEMENT boxart9 (#PCDATA)>		<!ELEMENT boxart10 (#PCDATA)>		<!ELEMENT snapshot1 (#PCDATA)>		<!ELEMENT snapshot2 (#PCDATA)>		<!ELEMENT snapshot3 (#PCDATA)>		<!ELEMENT snapshot4 (#PCDATA)>		<!ELEMENT snapshot5 (#PCDATA)>		<!ELEMENT snapshot6 (#PCDATA)>		<!ELEMENT snapshot7 (#PCDATA)>		<!ELEMENT snapshot8 (#PCDATA)>		<!ELEMENT snapshot9 (#PCDATA)>		<!ELEMENT snapshot10 (#PCDATA)>		<!ELEMENT banner1 (#PCDATA)>		<!ELEMENT banner2 (#PCDATA)>		<!ELEMENT banner3 (#PCDATA)>		<!ELEMENT banner4 (#PCDATA)>		<!ELEMENT banner5 (#PCDATA)>		<!ELEMENT banner6 (#PCDATA)>		<!ELEMENT banner7 (#PCDATA)>		<!ELEMENT banner8 (#PCDATA)>		<!ELEMENT banner9 (#PCDATA)>		<!ELEMENT banner10 (#PCDATA)>		<!ELEMENT clearlogo1 (#PCDATA)>		<!ELEMENT clearlogo2 (#PCDATA)>		<!ELEMENT clearlogo3 (#PCDATA)>		<!ELEMENT clearlogo4 (#PCDATA)>		<!ELEMENT clearlogo5 (#PCDATA)>		<!ELEMENT clearlogo6 (#PCDATA)>		<!ELEMENT clearlogo7 (#PCDATA)>		<!ELEMENT clearlogo8 (#PCDATA)>		<!ELEMENT clearlogo9 (#PCDATA)>		<!ELEMENT clearlogo10 (#PCDATA)>]>	<datafile>		<header>			<emu_name>Sega 32X</emu_name>			<emu_parser>NoIntro_parser.xml</emu_parser>			<emu_description>No-Intro_32X</emu_description>			<emu_category>Sega</emu_category>			<emu_version>08102015</emu_version>			<emu_date>03/03/2015</emu_date>			<emu_author>no-intro</emu_author>			<emu_homepage>http://www.no-intro.org</emu_homepage>			<emu_baseurl>http://archive.org/download/No-Intro-Collection_2015-03-03/Sega%20-%2032X.zip/Sega%20-%2032X%2F</emu_baseurl>			<emu_launcher>retroplayer</emu_launcher>			<emu_ext_launch_cmd>none</emu_ext_launch_cmd>			<emu_downloadpath>default</emu_downloadpath>			<emu_postdlaction>unzip_rom</emu_postdlaction>			<emu_comment>No Intro Sega 32X List by Zach Morris, removed all beta, and Non-USA games.The Sega 32X, codenamed Project Mars, is an add-on for the Mega Drive/Genesis video game console by Sega. Its aim was to increase the lifespan of the aging Mega Drive/Genesis system, which was facing stiff competition from the SNES. While connecting it to Mega Drive did increase its capabilities, reluctance to adapt due to the previous failure of the Mega-CD and the upcoming Sega Saturn system led to low sales and a short lifespan. It was distributed under the name Sega Super 32X in Japan, Sega Genesis 32X in North America, Sega Mega Drive 32X in the PAL region, and Sega Mega 32X in Brazil.Developer:  SegaManufacturer:  SegaCPU:  2 × SH-2 32-bit RISCMemory:  256 kB program RAMGraphics:  N/ASound:  Stereo 10-bit PWM (Pulse Width Modulation)Display:  320 × 240Media:  CartridgeMax. Controllers:  2			</emu_comment>			<emu_thumb>http://thegamesdb.net/banners/platform/boxart/33-1.jpg</emu_thumb>			<emu_banner>http://thegamesdb.net/banners/platform/banners/33-1.jpg</emu_banner>			<emu_fanart>http://upload.wikimedia.org/wikipedia/commons/a/a0/Sega-Genesis-Model2-32X.jpg</emu_fanart>			<emu_logo>http://upload.wikimedia.org/wikipedia/en/6/6c/Sega_32X_logo.png</emu_logo>			<emu_trailer>kxVOpWNlbDE</emu_trailer>		</header>			<game name="After Burner Complete ~ After Burner (Japan, USA)">					<description>After Burner Complete ~ After Burner (Japan, USA)</description>					<rom crc="204044c4" name="After Burner Complete ~ After Burner (Japan, USA).zip" size="2097152"/>					<plot>Strap into your lethal F14 Tomcat, kick-in the afterburner and set the skies alight!  You fly through multiple day and night missions over land and sea, picking off enemy targets as you lock and launch your deadly Sidewinder missiles.</plot>					<genre>Flight SimulatorShooter</genre>					<releasedate>01/13/1995</releasedate>					<nplayers>1</nplayers>					<fanart1>http://thegamesdb.net/banners/fanart/original/4912-1.jpg</fanart1>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/4912-1.jpg</boxart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/4912-1.jpg</boxart2>			</game>			<game name="Amazing Spider-Man, The - Web of Fire (USA)">					<description>Amazing Spider-Man, The - Web of Fire (USA)</description>					<rom crc="29dce257" name="Amazing Spider-Man, The - Web of Fire (USA).zip" size="3145728"/>					<plot>The game features side-scrolling action in which Spider-Man has to take on various enemy types which want to kill him. Besides the usual range of melee kicks and punches, he also sticks to walls and uses special attacks based on his web fluid. Creating spider web &quot;vines&quot; are used to swing from building to building; either required to cross gaps or simply to progress faster in the levels. Every use of his fluid decreases a web bar which, just like health, is refilled by picking up items floating in the game world. The first goal of the game is to rescue the superhero Daredevil, who then continues to help Spider-Man out: after activating the associated special attack, Daredevil covers the screen with his attacks.</plot>					<genre>Action</genre>					<releasedate>01/01/1996</releasedate>					<nplayers>1</nplayers>					<fanart1>http://thegamesdb.net/banners/fanart/original/4925-1.jpg</fanart1>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/4925-2.jpg</boxart1>					<boxart2>http://www.mobygames.com/images/covers/l/38643-the-amazing-spider-man-web-of-fire-sega-32x-front-cover.jpg</boxart2>					<boxart3>http://thegamesdb.net/banners/boxart/original/back/4925-2.jpg</boxart3>					<boxart4>http://www.mobygames.com/images/covers/l/38644-the-amazing-spider-man-web-of-fire-sega-32x-back-cover.jpg</boxart4>					<snapshot1>http://www.mobygames.com/images/shots/l/83855-the-amazing-spider-man-web-of-fire-sega-32x-screenshot-sega.jpg</snapshot1>					<snapshot2>http://www.mobygames.com/images/shots/l/83856-the-amazing-spider-man-web-of-fire-sega-32x-screenshot-again.jpg</snapshot2>					<snapshot3>http://www.mobygames.com/images/shots/l/83857-the-amazing-spider-man-web-of-fire-sega-32x-screenshot-marvel.jpg</snapshot3>					<snapshot4>http://www.mobygames.com/images/shots/l/83858-the-amazing-spider-man-web-of-fire-sega-32x-screenshot-the.jpg</snapshot4>					<snapshot5>http://www.mobygames.com/images/shots/l/83859-the-amazing-spider-man-web-of-fire-sega-32x-screenshot-main.jpg</snapshot5>					<snapshot6>http://www.mobygames.com/images/shots/l/83860-the-amazing-spider-man-web-of-fire-sega-32x-screenshot-the.jpg</snapshot6>					<snapshot7>http://www.mobygames.com/images/shots/l/83861-the-amazing-spider-man-web-of-fire-sega-32x-screenshot-fighting.jpg</snapshot7>					<snapshot8>http://www.mobygames.com/images/shots/l/83862-the-amazing-spider-man-web-of-fire-sega-32x-screenshot-high.jpg</snapshot8>					<snapshot9>http://www.mobygames.com/images/shots/l/83863-the-amazing-spider-man-web-of-fire-sega-32x-screenshot-wall.jpg</snapshot9>					<snapshot10>http://www.mobygames.com/images/shots/l/83864-the-amazing-spider-man-web-of-fire-sega-32x-screenshot-city.jpg</snapshot10>			</game>			<game name="BC Racers (USA)">					<description>BC Racers (USA)</description>					<rom crc="936c3d27" name="BC Racers (USA).zip" size="3145728"/>					<plot>Its pre-hysterical!  Millionaire playboy caveman Millstone Rockafella arranges a wild n wacky BC bike race, the winner of which receives the ultimate boulderdash bike.  Cool n crazy Cliff Ace has had his sunglasses set on a boulderdash bike since he was knee-high, so he signs up for the race - taking his cave-babe Roxy along for the ride!  The 32X pushes graphics to the limit with 256 colors for in-game graphics and full 24-bit for static display.  The stone-age never looked better!</plot>					<genre>Racing</genre>					<releasedate>01/01/1995</releasedate>					<nplayers>2</nplayers>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/4913-1.jpg</boxart1>					<boxart2>http://www.mobygames.com/images/covers/l/14463-bc-racers-sega-32x-front-cover.jpg</boxart2>					<boxart3>http://thegamesdb.net/banners/boxart/original/back/4913-1.jpg</boxart3>					<boxart4>http://www.mobygames.com/images/covers/l/14464-bc-racers-sega-32x-back-cover.jpg</boxart4>					<snapshot1>http://www.mobygames.com/images/shots/l/35793-bc-racers-sega-32x-screenshot-the-32x-version-lacks-the-animated.jpg</snapshot1>					<snapshot2>http://www.mobygames.com/images/shots/l/35794-bc-racers-sega-32x-screenshot-character-selection.jpg</snapshot2>					<snapshot3>http://www.mobygames.com/images/shots/l/35795-bc-racers-sega-32x-screenshot-the-32x-version-s-graphics-are.jpg</snapshot3>					<snapshot4>http://www.mobygames.com/images/shots/l/35796-bc-racers-sega-32x-screenshot-night-rider.jpg</snapshot4>					<snapshot5>http://www.mobygames.com/images/shots/l/35797-bc-racers-sega-32x-screenshot-the-desert-track.jpg</snapshot5>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/4913.png</clearlogo1>			</game>			<game name="Blackthorne (USA)">					<description>Blackthorne (USA)</description>					<rom crc="d1a60a47" name="Blackthorne (USA).zip" size="3145728"/>					<plot>Through the dark vastness of space, exiled prince Kyle Blackthorne returns to Tuul to avenge his murdered father and restore the shattered Lightstone.  The conqueror Sarlac opposes his vicious troops against the enraged prince.  But the evil lord will soon find out an army is not enough against a single fierce fighter with a vengeance!</plot>					<genre>ActionPlatform</genre>					<releasedate>01/01/1995</releasedate>					<nplayers>1</nplayers>					<videoid>YW-HYI-wqts</videoid>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/9074-1.jpg</boxart1>					<boxart2>http://www.mobygames.com/images/covers/l/14454-blackthorne-sega-32x-front-cover.jpg</boxart2>					<boxart3>http://thegamesdb.net/banners/boxart/original/back/9074-1.jpg</boxart3>					<boxart4>http://www.mobygames.com/images/covers/l/14455-blackthorne-sega-32x-back-cover.jpg</boxart4>					<snapshot1>http://www.mobygames.com/images/shots/l/35390-blackthorne-sega-32x-screenshot-title-screen.jpg</snapshot1>					<snapshot2>http://www.mobygames.com/images/shots/l/35391-blackthorne-sega-32x-screenshot-have-a-conversation-with-the.jpg</snapshot2>					<snapshot3>http://www.mobygames.com/images/shots/l/35392-blackthorne-sega-32x-screenshot-hiding-in-the-shadows.jpg</snapshot3>					<snapshot4>http://www.mobygames.com/images/shots/l/35393-blackthorne-sega-32x-screenshot-animated-introduction.jpg</snapshot4>					<snapshot5>http://www.mobygames.com/images/shots/l/35394-blackthorne-sega-32x-screenshot-i-might-just-be-the-chosen.jpg</snapshot5>					<snapshot6>http://www.mobygames.com/images/shots/l/35395-blackthorne-sega-32x-screenshot-backgrounds-get-a-nice-upgrade.jpg</snapshot6>					<snapshot7>http://www.mobygames.com/images/shots/l/35396-blackthorne-sega-32x-screenshot-the-desert.jpg</snapshot7>					<snapshot8>http://www.mobygames.com/images/shots/l/35397-blackthorne-sega-32x-screenshot-scary-castle.jpg</snapshot8>			</game>			<game name="Brutal Unleashed - Above the Claw (USA)">					<description>Brutal Unleashed - Above the Claw (USA)</description>					<rom crc="7a72c939" name="Brutal Unleashed - Above the Claw (USA).zip" size="3145728"/>					<plot>Under the watchful eye of the great master Dali Llama, the worlds greatest martial artists would return to a place they knew well Brutal Island.  Each will use their own unique mental and physical martial arts style and training, in a tournament to prove the worlds one true champion.Brutal, Above the Claw, is a brilliantly rendered game of humorous cartoon style combat, combined with depth, philosophy, and an attention to detail not found in any other fighting game.Go ahead and Unleash the Animal, its time to get Brutal.</plot>					<genre>Fighting</genre>					<releasedate>01/01/1995</releasedate>					<nplayers>2</nplayers>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/5295-1.jpg</boxart1>					<boxart2>http://www.mobygames.com/images/covers/l/31581-brutal-above-the-claw-sega-32x-front-cover.jpg</boxart2>					<boxart3>http://thegamesdb.net/banners/boxart/original/back/5295-1.jpg</boxart3>					<boxart4>http://www.mobygames.com/images/covers/l/31582-brutal-above-the-claw-sega-32x-back-cover.jpg</boxart4>					<boxart5>http://www.mobygames.com/images/covers/l/31583-brutal-above-the-claw-sega-32x-media.jpg</boxart5>					<snapshot1>http://www.mobygames.com/images/shots/l/456672-brutal-above-the-claw-sega-32x-screenshot-sega-logo.jpg</snapshot1>					<snapshot2>http://www.mobygames.com/images/shots/l/456673-brutal-above-the-claw-sega-32x-screenshot-first-title-screen.jpg</snapshot2>					<snapshot3>http://www.mobygames.com/images/shots/l/456674-brutal-above-the-claw-sega-32x-screenshot-second-title-screen.jpg</snapshot3>					<snapshot4>http://www.mobygames.com/images/shots/l/555504-brutal-above-the-claw-sega-32x-screenshot-a-character-shown.jpg</snapshot4>					<snapshot5>http://www.mobygames.com/images/shots/l/456675-brutal-above-the-claw-sega-32x-screenshot-main-menu.jpg</snapshot5>					<snapshot6>http://www.mobygames.com/images/shots/l/456676-brutal-above-the-claw-sega-32x-screenshot-options-screen.jpg</snapshot6>					<snapshot7>http://www.mobygames.com/images/shots/l/456677-brutal-above-the-claw-sega-32x-screenshot-name-entry.jpg</snapshot7>					<snapshot8>http://www.mobygames.com/images/shots/l/456678-brutal-above-the-claw-sega-32x-screenshot-character-selection.jpg</snapshot8>					<snapshot9>http://www.mobygames.com/images/shots/l/456679-brutal-above-the-claw-sega-32x-screenshot-vs-mode.jpg</snapshot9>					<snapshot10>http://www.mobygames.com/images/shots/l/456680-brutal-above-the-claw-sega-32x-screenshot-the-start-of-a-fight.jpg</snapshot10>			</game>			<game name="Chaotix ~ Knuckles' Chaotix (Japan, USA)">					<description>Chaotix ~ Knuckles' Chaotix (Japan, USA)</description>					<rom crc="d0b0b842" name="Chaotix ~ Knuckles' Chaotix (Japan, USA).zip" size="3145728"/>					<plot>A mysterious island rose from the sea shortly after the events of Sonic &amp; Knuckles. Dr. Robotnik discovered the island, and found a mysterious ring inscribed with descriptions of the Chaos Rings, ancient Rings infused with Chaos Emerald energy. In order to find these Rings, Robotnik built his base, the Newtrogic High Zone, on the island. Mighty the Armadillo, Espio the Chameleon, Vector the Crocodile, and Charmy Bee also arrived at the island, and ended up being captured by Robotnik and Metal Sonic, and placed in Robotnik's Combi Catcher machine. Knuckles, curious about the strange island, goes there as well, and manages to rescue Espio. The two then go on to stop Robotnik from getting the Chaos Rings.</plot>					<genre>Platform</genre>					<releasedate>04/21/1995</releasedate>					<nplayers>1</nplayers>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/2290-1.jpg</boxart1>					<boxart2>http://www.mobygames.com/images/covers/l/15649-knuckles-chaotix-sega-32x-front-cover.jpg</boxart2>					<boxart3>http://www.mobygames.com/images/covers/l/74459-knuckles-chaotix-sega-32x-front-cover.jpg</boxart3>					<boxart4>http://www.mobygames.com/images/covers/l/74447-knuckles-chaotix-sega-32x-front-cover.jpg</boxart4>					<boxart5>http://www.mobygames.com/images/covers/l/15650-knuckles-chaotix-sega-32x-back-cover.jpg</boxart5>					<boxart6>http://www.mobygames.com/images/covers/l/80071-knuckles-chaotix-sega-32x-media.jpg</boxart6>					<boxart7>http://www.mobygames.com/images/covers/l/74460-knuckles-chaotix-sega-32x-back-cover.jpg</boxart7>					<boxart8>http://www.mobygames.com/images/covers/l/117988-knuckles-chaotix-sega-32x-media.jpg</boxart8>					<boxart9>http://www.mobygames.com/images/covers/l/74448-knuckles-chaotix-sega-32x-back-cover.jpg</boxart9>					<boxart10>http://www.mobygames.com/images/covers/l/117989-knuckles-chaotix-sega-32x-media.jpg</boxart10>					<snapshot1>http://thegamesdb.net/banners/screenshots/2290-1.jpg</snapshot1>					<snapshot2>http://www.mobygames.com/images/shots/l/32523-knuckles-chaotix-sega-32x-screenshot-title-screen.jpg</snapshot2>					<snapshot3>http://www.mobygames.com/images/shots/l/32524-knuckles-chaotix-sega-32x-screenshot-vector-and-bomb.jpg</snapshot3>					<snapshot4>http://www.mobygames.com/images/shots/l/32525-knuckles-chaotix-sega-32x-screenshot-mighty-and-knuckles.jpg</snapshot4>					<snapshot5>http://www.mobygames.com/images/shots/l/32526-knuckles-chaotix-sega-32x-screenshot-knuckles-and-charmy.jpg</snapshot5>					<snapshot6>http://www.mobygames.com/images/shots/l/32527-knuckles-chaotix-sega-32x-screenshot-mighty-and-espio.jpg</snapshot6>					<snapshot7>http://www.mobygames.com/images/shots/l/32528-knuckles-chaotix-sega-32x-screenshot-mecha-sonic-makes-an-appearance.jpg</snapshot7>					<snapshot8>http://www.mobygames.com/images/shots/l/32529-knuckles-chaotix-sega-32x-screenshot-some-power-ups-make-you.jpg</snapshot8>					<snapshot9>http://www.mobygames.com/images/shots/l/32530-knuckles-chaotix-sega-32x-screenshot-the-bonus-levels-are-actually.jpg</snapshot9>					<snapshot10>http://www.mobygames.com/images/shots/l/460370-knuckles-chaotix-sega-32x-screenshot-there-is-a-training-mode.jpg</snapshot10>			</game>			<game name="Cyber Brawl ~ Cosmic Carnage (Japan, USA)">					<description>Cyber Brawl ~ Cosmic Carnage (Japan, USA)</description>					<rom crc="7c7be6a2" name="Cyber Brawl ~ Cosmic Carnage (Japan, USA).zip" size="3145728"/>					<plot>Cosmic Carnage is a one-on-one fighting game set in outer space. The story begins as a prison barge is hijacked by it's cargo in an escape attempt. The resulting chaos caused the barge to crash into a military cruiser. The impact caused extensive damage to both ships. There were only 8 survivors, 4 from each ship. What's worse, there's only one escape pod. You control one of the 8 survivors, and have to finish off all the others to escape with your life.</plot>					<genre>Fighting</genre>					<releasedate>03/02/1994</releasedate>					<nplayers>2</nplayers>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/4914-1.jpg</boxart1>					<boxart2>http://www.mobygames.com/images/covers/l/16222-cosmic-carnage-sega-32x-front-cover.jpg</boxart2>					<boxart3>http://www.mobygames.com/images/covers/l/35843-cosmic-carnage-sega-32x-front-cover.jpg</boxart3>					<boxart4>http://thegamesdb.net/banners/boxart/original/back/4914-1.jpg</boxart4>					<boxart5>http://www.mobygames.com/images/covers/l/16223-cosmic-carnage-sega-32x-back-cover.jpg</boxart5>					<boxart6>http://www.mobygames.com/images/covers/l/35844-cosmic-carnage-sega-32x-back-cover.jpg</boxart6>					<snapshot1>http://thegamesdb.net/banners/screenshots/4914-1.jpg</snapshot1>					<snapshot2>http://www.mobygames.com/images/shots/l/33230-cosmic-carnage-sega-32x-screenshot-title-screen.jpg</snapshot2>					<snapshot3>http://www.mobygames.com/images/shots/l/33231-cosmic-carnage-sega-32x-screenshot-the-story.jpg</snapshot3>					<snapshot4>http://www.mobygames.com/images/shots/l/33232-cosmic-carnage-sega-32x-screenshot-player-select.jpg</snapshot4>					<snapshot5>http://www.mobygames.com/images/shots/l/33233-cosmic-carnage-sega-32x-screenshot-cyclic-vs-talmac.jpg</snapshot5>					<snapshot6>http://www.mobygames.com/images/shots/l/33234-cosmic-carnage-sega-32x-screenshot-the-screen-zooms-out-as.jpg</snapshot6>					<snapshot7>http://www.mobygames.com/images/shots/l/33235-cosmic-carnage-sega-32x-screenshot-cyclic-vs-tyr.jpg</snapshot7>					<snapshot8>http://www.mobygames.com/images/shots/l/33236-cosmic-carnage-sega-32x-screenshot-naja-squeezes-her-opponents.jpg</snapshot8>			</game>			<game name="Doom (Japan, USA)">					<description>Doom (Japan, USA)</description>					<rom crc="208332fd" name="Doom (Japan, USA).zip" size="3145728"/>					<plot>All Hell has run amok!  Monstrous demons from another dimension use their gruesome talents to turn your space station into a blood-splattered slaughterhouse.They got black magic.  You got firepower.  Fireballs and lost souls face shotguns, chainsaws, and rocket launchers!Butcher the hordes of Hell.  Or get butchered, if you dont have the skill and pure guts to save your skin!</plot>					<genre>Shooter</genre>					<releasedate>01/01/1994</releasedate>					<nplayers>1-2s</nplayers>					<fanart1>http://thegamesdb.net/banners/fanart/original/4917-1.jpg</fanart1>					<fanart2>http://thegamesdb.net/banners/fanart/original/4917-2.jpg</fanart2>					<fanart3>http://thegamesdb.net/banners/fanart/original/4917-3.jpg</fanart3>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/4917-1.jpg</boxart1>					<boxart2>http://www.mobygames.com/images/covers/l/16222-cosmic-carnage-sega-32x-front-cover.jpg</boxart2>					<boxart3>http://www.mobygames.com/images/covers/l/35843-cosmic-carnage-sega-32x-front-cover.jpg</boxart3>					<boxart4>http://thegamesdb.net/banners/boxart/original/back/4917-1.jpg</boxart4>					<boxart5>http://www.mobygames.com/images/covers/l/16223-cosmic-carnage-sega-32x-back-cover.jpg</boxart5>					<boxart6>http://www.mobygames.com/images/covers/l/35844-cosmic-carnage-sega-32x-back-cover.jpg</boxart6>					<snapshot1>http://thegamesdb.net/banners/screenshots/4917-1.jpg</snapshot1>					<snapshot2>http://www.mobygames.com/images/shots/l/33230-cosmic-carnage-sega-32x-screenshot-title-screen.jpg</snapshot2>					<snapshot3>http://www.mobygames.com/images/shots/l/33231-cosmic-carnage-sega-32x-screenshot-the-story.jpg</snapshot3>					<snapshot4>http://www.mobygames.com/images/shots/l/33232-cosmic-carnage-sega-32x-screenshot-player-select.jpg</snapshot4>					<snapshot5>http://www.mobygames.com/images/shots/l/33233-cosmic-carnage-sega-32x-screenshot-cyclic-vs-talmac.jpg</snapshot5>					<snapshot6>http://www.mobygames.com/images/shots/l/33234-cosmic-carnage-sega-32x-screenshot-the-screen-zooms-out-as.jpg</snapshot6>					<snapshot7>http://www.mobygames.com/images/shots/l/33235-cosmic-carnage-sega-32x-screenshot-cyclic-vs-tyr.jpg</snapshot7>					<snapshot8>http://www.mobygames.com/images/shots/l/33236-cosmic-carnage-sega-32x-screenshot-naja-squeezes-her-opponents.jpg</snapshot8>					<banner1>http://thegamesdb.net/banners/graphical/4917-g.jpg</banner1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/4917.png</clearlogo1>			</game>			<game name="Golf Magazine 36 Great Holes Starring Fred Couples (Japan, USA)">					<description>Golf Magazine 36 Great Holes Starring Fred Couples (Japan, USA)</description>					<rom crc="d3d0a2fe" name="Golf Magazine 36 Great Holes Starring Fred Couples (Japan, USA).zip" size="3145728"/>					<plot>There are seven different modes (Stroke Play, Tournament, Skins, Shoot-out, Scramble, Practice and Match Play) and three different types of golf club heads including wood, metal and graphite. There is a battery back-up to keep track of 16 different categories of stats and does feature the voice of Fred Couples, even though he is not a playable character.</plot>					<genre>Sports</genre>					<releasedate>01/01/1994</releasedate>					<nplayers>1-8s</nplayers>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/4911-1.jpg</boxart1>					<boxart2>http://www.mobygames.com/images/covers/l/162554-golf-magazine-presents-36-great-holes-starring-fred-couples-sega-32x-front-cover.jpg</boxart2>					<boxart3>http://www.mobygames.com/images/covers/l/164593-golf-magazine-presents-36-great-holes-starring-fred-couples-sega-32x-front-cover.jpg</boxart3>					<boxart4>http://thegamesdb.net/banners/boxart/original/back/4911-1.jpg</boxart4>					<boxart5>http://www.mobygames.com/images/covers/l/162555-golf-magazine-presents-36-great-holes-starring-fred-couples-sega-32x-back-cover.jpg</boxart5>					<boxart6>http://www.mobygames.com/images/covers/l/164594-golf-magazine-presents-36-great-holes-starring-fred-couples-sega-32x-back-cover.jpg</boxart6>					<boxart7>http://www.mobygames.com/images/covers/l/164595-golf-magazine-presents-36-great-holes-starring-fred-couples-sega-32x-media.jpg</boxart7>					<snapshot1>http://www.mobygames.com/images/shots/l/555487-golf-magazine-presents-36-great-holes-starring-fred-couples.jpg</snapshot1>					<snapshot2>http://www.mobygames.com/images/shots/l/463953-golf-magazine-presents-36-great-holes-starring-fred-couples.jpg</snapshot2>					<snapshot3>http://www.mobygames.com/images/shots/l/555488-golf-magazine-presents-36-great-holes-starring-fred-couples.jpg</snapshot3>					<snapshot4>http://www.mobygames.com/images/shots/l/463954-golf-magazine-presents-36-great-holes-starring-fred-couples.jpg</snapshot4>					<snapshot5>http://www.mobygames.com/images/shots/l/463955-golf-magazine-presents-36-great-holes-starring-fred-couples.jpg</snapshot5>					<snapshot6>http://www.mobygames.com/images/shots/l/555491-golf-magazine-presents-36-great-holes-starring-fred-couples.jpg</snapshot6>					<snapshot7>http://www.mobygames.com/images/shots/l/555492-golf-magazine-presents-36-great-holes-starring-fred-couples.jpg</snapshot7>					<snapshot8>http://www.mobygames.com/images/shots/l/555493-golf-magazine-presents-36-great-holes-starring-fred-couples.jpg</snapshot8>					<snapshot9>http://www.mobygames.com/images/shots/l/555494-golf-magazine-presents-36-great-holes-starring-fred-couples.jpg</snapshot9>					<snapshot10>http://www.mobygames.com/images/shots/l/555495-golf-magazine-presents-36-great-holes-starring-fred-couples.jpg</snapshot10>			</game>			<game name="Kolibri (USA, Europe)">					<description>Kolibri (USA, Europe)</description>					<rom crc="20ca53ef" name="Kolibri (USA, Europe).zip" size="3145728"/>					<plot>Kolibri is a hummingbird hero in this unusual side scrolling shooter for the 32X. Deep inside the earth's core, there is a crystal from another world. This crystal is the earth's life force, and essential to it's survival. One day, a dark crystal falls from the sky and damages the earth's crystal. Desperate, the earth's crystal rockets to the surface and empowers Kolibri with the abilities he needs to defeat the dark crystal.</plot>					<genre>Shooter</genre>					<releasedate>01/01/1995</releasedate>					<nplayers>1</nplayers>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/2609-1.jpg</boxart1>					<boxart2>http://www.mobygames.com/images/covers/l/15568-kolibri-sega-32x-front-cover.jpg</boxart2>					<boxart3>http://thegamesdb.net/banners/boxart/original/back/2609-1.jpg</boxart3>					<boxart4>http://www.mobygames.com/images/covers/l/15569-kolibri-sega-32x-back-cover.jpg</boxart4>					<snapshot1>http://thegamesdb.net/banners/screenshots/2609-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/2609-2.jpg</snapshot2>					<snapshot3>http://www.mobygames.com/images/shots/l/32435-kolibri-sega-32x-screenshot-title-screen.jpg</snapshot3>					<snapshot4>http://www.mobygames.com/images/shots/l/153518-kolibri-sega-32x-screenshot-main-menu.jpg</snapshot4>					<snapshot5>http://www.mobygames.com/images/shots/l/32436-kolibri-sega-32x-screenshot-it-s-kolibri.jpg</snapshot5>					<snapshot6>http://www.mobygames.com/images/shots/l/32437-kolibri-sega-32x-screenshot-kolibri-partakes-in-sweet-nectar.jpg</snapshot6>					<snapshot7>http://www.mobygames.com/images/shots/l/32438-kolibri-sega-32x-screenshot-clear-the-bugs-away-from-the-flowers.jpg</snapshot7>					<snapshot8>http://www.mobygames.com/images/shots/l/32439-kolibri-sega-32x-screenshot-check-out-those-backgrounds.jpg</snapshot8>					<snapshot9>http://www.mobygames.com/images/shots/l/153519-kolibri-sega-32x-screenshot-our-kolibri-is-really-powe